<html>
    <head>
        <title>Account Administrator Homepage</title>
    </head>
    <body>
        <h1>Account Administrator Homepage</h1>
        <ul>
            <li><a href="/AddCustomer">Add a new customer</a></li>
            <li><a href="/CreateAccount">Create a new account</a></li>
            <li><a href="/CustomerList">View all customers</a></li>
            <li><a href="/AccountTypes">Change account types</a></li>
            <li><a href="/BankAdmin">Administration</a></li>
        </ul>
    </body>
</html>