<html>
    <head>
        <title>Found Account</title>
    </head>
    <body>
        <h2>Found Account</h2>
        <table border="1" cellpadding="10">
            <tr>
                <td><b>Customer Account Number</b></td>
                <td><b>Name</b></td>
                <td><b>Nickname</b></td>
                <td><b>Address</b></td>
            </tr>
            <tr>
                <td>$account$</td>
                <td align="left">$account.owner.name$</td>
                <td align="right">$account.owner.nickName$</td>
                <td align="right">$account.owner.address$</td>
            </tr>
        </table>
    </body>
</html>
